chamber_of_commerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('record_app/', include('record_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('',RedirectView.as_view(url='accounts/login/'), {'next_page': '/record_app/'}),
]

record_app/urls.py
from django.urls import path
from .views import HomeView, ThankyouView, EmployeeCreateView, EmployeesListView, FilesCreateView, FilesListView, IncomingCreateView, IncomingListView, IncomingDetailView, IncomingUpdateView, IncomingDeleteView, OutgoingCreateView, OutgoingListView, OutgoingDetailView, OutgoingUpdateView, OutgoingDeleteView

app_name = 'record_app'

urlpatterns = [
    path('',HomeView.as_view(), name='home'),
    path('thankyou/',ThankyouView.as_view(), name='thank_you'),
    path('create_employee/', EmployeeCreateView.as_view(), name='create_employee'),
    path('list_employees/', EmployeesListView.as_view(), name='list_employees'),
    path('create_file/', FilesCreateView.as_view(), name='create_files'),
    path('list_files/', FilesListView.as_view(), name="list_files"),
    path('create_incoming/', IncomingCreateView.as_view(), name="create_incoming"),
    path('list_incoming/', IncomingListView.as_view(), name="list_incoming"),
    path('detail_incoming/<int:pk>', IncomingDetailView.as_view(), name="detail_incoming"),
    path('update_incoming/<int:pk>', IncomingUpdateView.as_view(), name="update_incoming"),
    path('delete_incoming/<int:pk>', IncomingDeleteView.as_view(), name="delete_incoming"),
    path('create_outgoing/', OutgoingCreateView.as_view(), name="create_outgoing"),
    path('list_outgoing/', OutgoingListView.as_view(), name="list_outgoing"),
    path('detail_outgoing/<int:pk>', OutgoingDetailView.as_view(), name="detail_outgoing"),
    path('update_outgoing/<int:pk>', OutgoingUpdateView.as_view(), name="update_outgoing"),
    path('delete_outgoing/<int:pk>', OutgoingDeleteView.as_view(), name="delete_outgoing"),
]

record_app/models.py
from django.db import models

# Create your models here.
class Employees(models.Model):
    name = models.CharField(max_length=100)
    designation = models.CharField(max_length=100)
    department = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.name}, {self.designation}, {self.department}"


class Files(models.Model):
    file_number = models.CharField(max_length=50)
    description = models.CharField(max_length=300, null=True, blank=True)
    
    def __str__(self):
        return f"{self.file_number}"


class Incoming(models.Model):
    document_number =models.IntegerField(unique=True)
    date_received =models.DateField(auto_now_add=False, auto_now=False)

    DOCUMENT_TYPE = [
        ('EM', 'Email'),
        ('LR', 'Letter'),
        ('OT', 'OTHER'),
    ]
    
    document_type = models.CharField(max_length=2,choices=DOCUMENT_TYPE)
    file_number = models.ForeignKey(Files, on_delete=models.CASCADE)
    received_from = models.CharField(max_length=100, null=True, blank=True)
    subject = models.CharField(max_length=300)
    description =models.TextField()
    marked_to = models.ForeignKey(Employees, null=True, on_delete=models.CASCADE, blank=True)

    STATUS = [
        ('FL', 'Filed'),
        ('IP', 'InProcess'),
    ]

    status = models.CharField(max_length=2,choices=STATUS, null=True, blank=True)
    url = models.URLField(null=True, default="https://www.google.com/", blank=True)

    def __str__(self):
        return f"ID: {self.document_number}, Subject: {self.subject}"

class Outgoing(models.Model):
    document_number = models.IntegerField(unique=True)
    date_dispatched = models.DateField(auto_now_add=False, auto_now=False)
    DOCUMENT_TYPE = [
        ('EM', 'Email'),
        ('LR', 'Letter'),
        ('OT', 'OTHER'),
    ]
    
    document_type = models.CharField(max_length=2,choices=DOCUMENT_TYPE)
    file_number = models.ForeignKey(Files, on_delete=models.CASCADE)
    sent_to = models.CharField(max_length=300, null=True, blank=True)
    subject = models.CharField(max_length=300)
    description = models.TextField()
    dispatched_by = models.ForeignKey(Employees, null=True, on_delete=models.CASCADE, blank=True)

    STATUS = [
        ('DP', 'Dispatched'),
        ('DL', 'Delivered'),
        ('RT', 'Returned'),
    ]
    status = models.CharField(max_length=2,choices=STATUS, blank=True)
    url = models.URLField(null=True, default="https://www.google.com/", blank=True)

    def __str__(self):
        return f"ID: {self.document_number}, Subject: {self.subject}"

record_app/views.py
from django.shortcuts import render
from django.urls import reverse,reverse_lazy
from django.views.generic import TemplateView, CreateView, ListView, DetailView, UpdateView, DeleteView
from record_app.models import Employees, Files, Incoming, Outgoing
# Create your views here.
# def home_view(request):
#     return render(request, 'record_app/home.html')

class HomeView(TemplateView):
    template_name = 'record_app/home.html'

class ThankyouView(TemplateView):
    template_name = 'record_app/thankyou.html'

class EmployeeCreateView(CreateView):
    model = Employees
    fields = "__all__"
    success_url = reverse_lazy('record_app:thank_you')

class EmployeesListView(ListView):
    model = Employees
    queryset = Employees.objects.order_by("department")
    context_object_name = 'employees'

class FilesCreateView(CreateView):
    model = Files
    fields = "__all__"
    success_url = reverse_lazy('record_app:thank_you')

class FilesListView(ListView):
    model = Files
    context_object_name = 'files'

class IncomingCreateView(CreateView):
    model = Incoming
    fields = "__all__"
    success_url = reverse_lazy('record_app:thank_you')

# class IncomingListView(ListView):
#     model = Incoming
#     queryset = Incoming.objects.order_by("document_number")
#     context_object_name = 'incomings'

from django.db.models import Q

class IncomingListView(ListView):
    model = Incoming
    queryset = Incoming.objects.order_by("document_number")
    context_object_name = 'incomings'
    paginate_by = 10

    def get_queryset(self):
        search_term = self.request.GET.get('q')
        if search_term:
            queryset = Incoming.objects.filter(Q(subject__icontains=search_term) | Q(description__icontains=search_term))
        else:
            queryset = Incoming.objects.all()
        return queryset



class IncomingDetailView(DetailView):
    model = Incoming

class IncomingUpdateView(UpdateView):
    model = Incoming 
    fields = "__all__"
    success_url = reverse_lazy('record_app:thank_you')

class IncomingDeleteView(DeleteView):
    model = Incoming
    success_url = reverse_lazy('record_app:list_incoming')

class OutgoingCreateView(CreateView):
    model = Outgoing
    fields = "__all__"
    success_url = reverse_lazy('record_app:thank_you')

# class OutgoingListView(ListView):
#     model = Outgoing
#     queryset = Outgoing.objects.order_by("document_number")
#     context_object_name = 'outgoings'

class OutgoingListView(ListView):
    model = Outgoing
    queryset = Outgoing.objects.order_by("document_number")
    context_object_name = 'outgoings'
    paginate_by = 10

    def get_queryset(self):
        search_term = self.request.GET.get('q')
        if search_term:
            queryset = Outgoing.objects.filter(Q(subject__icontains=search_term) | Q(description__icontains=search_term))
        else:
            queryset = Outgoing.objects.all()
        return queryset

class OutgoingDetailView(DetailView):
    model = Outgoing

class OutgoingUpdateView(UpdateView):
    model = Outgoing
    fields = "__all__"
    success_url = reverse_lazy('record_app:thank_you')

class OutgoingDeleteView(DeleteView):
    model = Outgoing
    success_url = reverse_lazy('record_app:list_outgoing')


record_app/templates/record_app/employees_form.html
<h1>Employees Form</h1>
<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="submit">

</form>

record_app/templates/record_app/employees_list.html
<h1>List of all Employees</h1>
<ul>
    {% for employee in employees %}
        <li>{{employee.name}}, {{employee.designation}}, {{employee.department}}</li>
    {% endfor %}
</ul>

record_app/templates/record_app/files_form.html
<h1>Files Form</h1>
<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="submit">

</form>

record_app/templates/record_app/files_list.html
<h1>List of all Files</h1>
<ul>
    {% for file in files %}
        <li>{{file.file_number}}, {{file.description}}</li>
    {% endfor %}
</ul>

record_app/templates/record_app/home.html
<h1>This is Home Page</h1>
<ul>
    <li>
        <a href="{% url "record_app:home" %}">home</a>
    </li>
    <li>
        <a href="{% url "record_app:thank_you" %}">thank you</a>
    </li>
    <li>
        <a href="{% url "record_app:create_employee" %}">Create Employee</a>
    </li>
    <li>
        <a href="{% url "record_app:list_employees" %}">List Employees</a>
    </li>
    <li>
        <a href="{% url "record_app:create_files" %}">Create Files</a>
    </li>
    <li>
        <a href="{% url "record_app:list_files" %}">List Files</a>
    </li>
    <li>
        <a href="{% url "record_app:create_incoming" %}">Create Incoming</a>
    </li>

    <li>
        <a href="{% url "record_app:list_incoming" %}">list Incoming</a>
    </li>

    <li>
        <a href="{% url "record_app:create_outgoing" %}">Create Outgoing</a>
    </li>

    <li>
        <a href="{% url "record_app:list_outgoing" %}">List Outgoing</a>
    </li>



</ul>


{% if user.is_authenticated %}
	<p> you are logged in </p>
	<p> Welcome: {{user.get_username}} </p>
	<a href="{% url 'logout' %}">click here to logout</a>

{% else %}
	<p>You are not logged in</p>
	<a href="{% url 'login' %}">click here to login</a>
{% endif %}



record_app/templates/record_app/incoming_confirm_delete.html
<h1>Are you you want to delete this incoming record?</h1>
<h2>{{incoming}}</h2>

<form method="POST">
    {% csrf_token %}
    <input type="submit" value="Confirm Delete">

</form>

record_app/templates/record_app/incoming_detail.html
<h1>Incoming Details</h1>
<table>
    <ul>
        <li>Document Number: {{incoming.document_number}}</li>
        <li>Date Received: {{incoming.date_received}}</li>
        <li>Document Type: {{incoming.document_type}}</li>
        <li>File number: {{incoming.file_number}}</li>
        <li>Received From: {{incoming.received_from}}</li>
        <li>Subject: {{incoming.subject}}</li>
        <li>Description: {{incoming.description}}</li>
        <li>Marked to: {{incoming.marked_to}}</li>
        <li>Status: {{incoming.status}}</li>
        <li>Url: {{incoming.url}}</li>
    </ul>
</table>

record_app/templates/record_app/incoming_form.html
<h1>Incoming Form</h1>
<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="submit">

</form>

record_app/templates/record_app/incoming_list.html
<h1>List of all Incomings with Search</h1>
<form action="{% url 'record_app:list_incoming' %}" method="get">
    <input type="text" name="q" value="{{ request.GET.q }}">
    <button type="submit">Search</button>
</form>
<table>
    {% for incoming in incomings %}
    <tr>
        <td>{{incoming.document_number}}</td>
        <td>{{incoming.subject}}</td>
        <td>{{incoming.description}}</td>
        <td><a href="/record_app/detail_incoming/{{incoming.id}}">Details</a></td>
        <td><a href="/record_app/update_incoming/{{incoming.id}}">Update</a></td>
        <td><a href="/record_app/delete_incoming/{{incoming.id}}">Delete</a></td>
        
    </tr>
    {% empty %}
    <tr>No record found.</tr>
    {% endfor %}
</table>


record_app/templates/record_app/outgoing_confirm_delete.html
<h1>Are you you want to delete this outgoing record?</h1>
<h2>{{outgoing}}</h2>

<form method="POST">
    {% csrf_token %}
    <input type="submit" value="Confirm Delete">

</form>

record_app/templates/record_app/outgoing_detail.html
<h1>outgoing Details</h1>
<table>
    <ul>
        <li>Document Number: {{outgoing.document_number}}</li>
        <li>Date Received: {{outgoing.date_received}}</li>
        <li>Document Type: {{outgoing.document_type}}</li>
        <li>File number: {{outgoing.file_number}}</li>
        <li>Received From: {{outgoing.received_from}}</li>
        <li>Subject: {{outgoing.subject}}</li>
        <li>Description: {{outgoing.description}}</li>
        <li>Marked to: {{outgoing.marked_to}}</li>
        <li>Status: {{outgoing.status}}</li>
        <li>Url: {{outgoing.url}}</li>
    </ul>
</table>

record_app/templates/record_app/outgoing_form.html
<h1>Outgoing Form</h1>
<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="submit">

</form>

record_app/templates/record_app/outgoing_list.html
<h1>List of all outgoings with Search</h1>
<form action="{% url 'record_app:list_outgoing' %}" method="get">
    <input type="text" name="q" value="{{ request.GET.q }}">
    <button type="submit">Search</button>
</form>
<table>
    {% for outgoing in outgoings %}
    <tr>
        <td>{{outgoing.document_number}}</td>
        <td>{{outgoing.subject}}</td>
        <td>{{outgoing.description}}</td>
        <td><a href="/record_app/detail_outgoing/{{outgoing.id}}">Details</a></td>
        <td><a href="/record_app/update_outgoing/{{outgoing.id}}">Update</a></td>
        <td><a href="/record_app/delete_outgoing/{{outgoing.id}}">Delete</a></td>
        
    </tr>
    {% empty %}
    <tr>No record found.</tr>
    {% endfor %}
</table>


record_app/templates/record_app/thankyou.html
<h1>Thank you</h1>